/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.lavcraft.examples.cucumber;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
